Number of parameters in the model:  540773
Traceback (most recent call last):
  File "/home/gb21553/OneDrive/CAVIA/regression/main.py", line 14, in <module>
    logger = cavia.run(args, log_interval=10, rerun=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/OneDrive/CAVIA/regression/cavia.py", line 139, in run
    train_outputs = model(train_inputs, t_eval)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/miniconda3/envs/torch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/OneDrive/CAVIA/regression/cavia_model.py", line 279, in forward
    pred_y = odeint(newodefunc, x, t_eval, method='dopri5')[:,...]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/miniconda3/envs/torch/lib/python3.11/site-packages/torchdiffeq/_impl/odeint.py", line 77, in odeint
    solution = solver.integrate(t)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/miniconda3/envs/torch/lib/python3.11/site-packages/torchdiffeq/_impl/solvers.py", line 30, in integrate
    solution[i] = self._advance(t[i])
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/miniconda3/envs/torch/lib/python3.11/site-packages/torchdiffeq/_impl/rk_common.py", line 194, in _advance
    self.rk_state = self._adaptive_step(self.rk_state)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/miniconda3/envs/torch/lib/python3.11/site-packages/torchdiffeq/_impl/rk_common.py", line 255, in _adaptive_step
    y1, f1, y1_error, k = _runge_kutta_step(self.func, y0, f0, t0, dt, t1, tableau=self.tableau)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/miniconda3/envs/torch/lib/python3.11/site-packages/torchdiffeq/_impl/rk_common.py", line 76, in _runge_kutta_step
    f = func(ti, yi, perturb=perturb)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/miniconda3/envs/torch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/miniconda3/envs/torch/lib/python3.11/site-packages/torchdiffeq/_impl/misc.py", line 189, in forward
    return self.base_func(t, y)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/OneDrive/CAVIA/regression/cavia_model.py", line 278, in newodefunc
    return self.odefunc(t,x,self.context_params,)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/miniconda3/envs/torch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/OneDrive/CAVIA/regression/cavia_model.py", line 165, in forward
    x = self.net(x) 
        ^^^^^^^^^^^
  File "/home/gb21553/miniconda3/envs/torch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/miniconda3/envs/torch/lib/python3.11/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/gb21553/miniconda3/envs/torch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/OneDrive/CAVIA/regression/cavia_model.py", line 127, in forward
    return self.activation(x)
           ^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/miniconda3/envs/torch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gb21553/OneDrive/CAVIA/regression/cavia_model.py", line 115, in forward
    return (x * torch.sigmoid_(x * F.softplus(beta))).div_(1.1).reshape(-1, self.groups * n_ch_group, *t)
            ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 23.69 GiB total capacity; 15.48 GiB already allocated; 61.88 MiB free; 22.05 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
